# version: "3.3"
# Please refer to: https://blog.laoda.de/archives/docker-compose-install-matrix-element
# Reminder: You might need a translator for reading this site.

services:
  synapse:
    image: "matrixdotorg/synapse:latest"
    container_name: "synapse"
    restart: unless-stopped
    # If you want to use PostgreSQL instead of SQLite, you can uncomment the following lines and provide your PostgreSQL credentials.
    # depends_on:
    #   - db
    ports:
      - "8008:8008"
      # You can use other open ports on your host if 8008 is not available, e.g. "2435:8008".
      # However, port 8448 is strongly not recommended as it is reserved for federation and should be used for that purpose only.
    volumes:
      - "/opt/matrix/synapse-data:/data"
    # You can comment out the "environment" section if you want to use the default configuration in homeserver.yaml.
    environment:
      # You must replace "synapse.yourhost.domain" with your actual domain name.
      VIRTUAL_HOST: "synapse.yourhost.domain"
      VIRTUAL_PORT: "8008" # YOU SHOULD NOT MODIFY THIS
      LETSENCRYPT_HOST: "synapse.yourhost.domain"
      SYNAPSE_SERVER_NAME: "synapse.yourhost.domain"
      SYNAPSE_REPORT_STATS: "no"
  # You can uncomment the following lines to use PostgreSQL instead of SQLite.
  # However, you must change "sqlite3" to "psycopg2" (database.name) in homeserver.yaml
  # db:
  #   image: docker.io/postgres:17 # please use specific version instead of "latest" here
  #   container_name: "postgresql-17"
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=synapse
  #     - POSTGRES_PASSWORD=synapse
  #     - POSTGRES_INITDB_ARGS=--encoding='UTF8' --lc-collate='C' --lc-ctype='C'
  #   volumes:
  #     - /opt/synapse/postgresql:/var/lib/postgresql/17/main/
  element-web:
    ports:
      - "8009:80"
    image: vectorim/element-web
    container_name: "element-web"
    restart: unless-stopped